### ISSUE TITLE
Unable to use the project

### ISSUE THREAD

**Issue by andreaselia** [fyelci/serverless-openai-chatgpt-stream#1]
Hi there,

I've been trying to get this working, but keep running into the issue below.

Issue:
```
2023-07-30T08:49:26.179Z d6bf5a4e-c18e-4b84-b526-fa1416f1566c ERROR TypeError: The "streams" argument must be specified at new NodeError (node:internal/errors:399:5) at pipelineImpl (node:internal/streams/pipeline:193:11) at node:stream/promises:31:5 at new Promise (<anonymous>) at pipeline (node:stream/promises:20:10) at /var/src/handlers/chat.ts:73:9 at Generator.next (<anonymous>) at fulfilled (/var/task/src/handlers/chat.js:5:58) at processTicksAndRejections (node:internal/process/task_queues:95:5) { code: 'ERR_MISSING_ARGS' }
```

I run and populate:
```bash
cp .env.example .env
```

Followed by:
```bash
npm install
npm run deploy
```

I added the environment variables into Serverless too, and everything seems to go well and logs the event body correctly up until the issue above.

**Comment by andreaselia** [comment]
I updated the pipeline to use the iterable streams parameter, but now the response is consistently `{"Message":null}`

**Comment by fyelci** [comment]
Please make sure your node version is 18 when you're deploying the project. 
Double-check your `.env` file and put your openai API key there. 

You shouldn't need to make any changes to the code to make it work. I just tried it with a fresh installation, it works as expected.

**Comment by andreaselia** [comment]
Ah I see, your local environment version of Node has to be 18 too, not just set in serverless config.

Thank you @fyelci 👍  I ended up achieving what I wanted to achieve via manual setup in the AWS console in the end.
